### ISSUE TITLE
not checking that required --expect-workers is set when --manager is enabled

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#292]
We build a rust bin called `gti` and are able to run this fine against a server.   

When we try to evolve toward gaggle we hit this error (NNG is built without error):

```bash 
$ podman run --env RUST_BACKTRACE=full --network="host" --rm -ti gti /usr/local/bin/gti --host http://127.0.0.1:5000 --manager
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/goose-0.11.2/src/manager.rs:49:54
stack backtrace:
   0:     0x55d3970757c0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d3970757c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d3970757c0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d3970757c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d397094a2f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x55d39706f982 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x55d3970778d5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d3970778d5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d3970778d5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x55d397077383 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x55d397077edd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x55d397077a47 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x55d397075c7c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d3970779d9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x55d396cbdcb1 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x55d396cbdbfd - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x55d396d09034 - goose::manager::distribute_users::h6659e311788ff541
  17:     0x55d396d854ca - goose::manager::manager_main::{{closure}}::hdb47f8869f4a3106
  18:     0x55d396d3c5c6 - tokio::park::thread::CachedParkThread::block_on::h91c1b728afd1f277
  19:     0x55d396db02b3 - tokio::runtime::Runtime::block_on::hd108f4df90059178
  20:     0x55d396ce5248 - goose::GooseAttack::execute::h25ccd1da4b358d74
  21:     0x55d396cd7cea - gti::main::hd499506f92406bf7
  22:     0x55d396cc9ef3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3af067c8f5b93010
  23:     0x55d396cc9f18 - std::rt::lang_start::{{closure}}::hcea87158100e28da
  24:     0x55d3970783da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  25:     0x55d3970783da - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  26:     0x55d3970783da - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  27:     0x55d3970783da - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  28:     0x55d3970783da - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  29:     0x55d396cd7fc2 - main
  30:     0x7f1f927b809b - __libc_start_main
  31:     0x55d396cbe39a - _start
  32:                0x0 - <unknown>
```

**Comment by jeremyandrews** [comment]
What parameters did you start the manage with?

The line number suggests the comment was wrong and you get there with no users defined. Perhaps add “—users” when you start the manager?

**Comment by bbros-dev** [comment]
if we add `--expect-workers 1` there is no error just a empty console.  So its a missing option/setting error?

We assume it started correctly and is awaiting the workers?

**Comment by bbros-dev** [comment]
If we add both `--expect-workers 1 --users 1` we get the empty console.

If we add only `--users 1` we get:

```bash
$ podman run --env RUST_BACKTRACE=full --network="host" --rm -ti gti /usr/local/bin/gti --host http://127.0.0.1:5000 --manager --users 1 &>goose.log
$ cat goose.log
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/goose-0.11.2/src/manager.rs:49:54
stack backtrace:
   0:     0x556a3557c7c0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556a3557c7c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556a3557c7c0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556a3557c7c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556a3559ba2f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x556a35576982 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x556a3557e8d5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556a3557e8d5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556a3557e8d5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x556a3557e383 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x556a3557eedd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x556a3557ea47 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x556a3557cc7c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x556a3557e9d9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x556a351c4cb1 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x556a351c4bfd - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x556a35210034 - goose::manager::distribute_users::h6659e311788ff541
  17:     0x556a3528c4ca - goose::manager::manager_main::{{closure}}::hdb47f8869f4a3106
  18:     0x556a352435c6 - tokio::park::thread::CachedParkThread::block_on::h91c1b728afd1f277
  19:     0x556a352b72b3 - tokio::runtime::Runtime::block_on::hd108f4df90059178
  20:     0x556a351ec248 - goose::GooseAttack::execute::h25ccd1da4b358d74
  21:     0x556a351decea - gti::main::hd499506f92406bf7
  22:     0x556a351d0ef3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3af067c8f5b93010
  23:     0x556a351d0f18 - std::rt::lang_start::{{closure}}::hcea87158100e28da
  24:     0x556a3557f3da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  25:     0x556a3557f3da - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  26:     0x556a3557f3da - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  27:     0x556a3557f3da - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  28:     0x556a3557f3da - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  29:     0x556a351defc2 - main
  30:     0x7f3da600909b - __libc_start_main
  31:     0x556a351c539a - _start
  32:                0x0 - <unknown>

```

**Comment by bbros-dev** [comment]
Reviewing the blog post we expected the errors shown there.

**Comment by jeremyandrews** [comment]
There seems to have been a regression, I've updated the title of the issue. It's an easy fix, and a test should be added to be sure this doesn't regress again.

**Comment by jeremyandrews** [comment]
The blog referenced above for anyone else reading this issue:
https://www.tag1consulting.com/blog/show-me-how-flock-flies-working-gaggle-goose

In general I recommend using the `-v` flag when running Goose, or use these two options together `-g --log-file goose.log` and keep an eye on the generated log.

A useful overview on using/debugging-with Goose:
https://www.tag1consulting.com/blog/real-life-goose-load-testing
